server:
  port: 8082
  servlet:
    contextPath: /user

spring:
  application:
    name: user-service

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/shopping
    username: root
    password: 1qaz2wsx

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

flyway:
  enabled: true
  url: jdbc:mysql://localhost:3306/shopping
  user: root
  password: 1qaz2wsx
  locations: classpath:db/migration
  baselineOnMigrate: true