server:
  port: 8003
  servlet:
    contextPath : /product

spring:
  jpa:
    hibernate :
      ddl-auto: update

  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: password1234

flyway:
  baselineOnMigrate: true

eureka:
  client:
    service-url:
      defaultZone : http://192.168.108.73:9001/eureka