server:
  port: 8081
  servlet:
    contextPath: /payment

spring:
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: payment-service

  cloud:
    config:
      override-system-properties: false
      allow-override: true
      override-none: true

  datasource:
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: m1234567

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

flyway:
  enabled: true
  url: jdbc:mysql://localhost:3306/payment
  user: root
  password: m1234567
  locations: classpath:db/migration
  baselineOnMigrate: true
